# Generated by Django 5.0.1 on 2024-01-28 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('excursion', models.CharField(max_length=100)),
                ('provedor', models.CharField(max_length=100)),
                ('ppp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Extension', models.CharField(max_length=40, null=True)),
                ('FileName', models.CharField(max_length=200, null=True)),
                ('Doc_Content', models.BinaryField(null=True)),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichasTecnicas', to='crud.tour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
