# Generated by Django 5.0.1 on 2024-02-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='Tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichasTecnicas', to='crud.tour'),
        ),
    ]
