# Generated by Django 5.0.1 on 2024-02-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_tour_figma_boleto_guiado_hotel_fichatecnicahotel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tren',
            old_name='precioNino',
            new_name='precioNinio',
        ),
    ]
