# Generated by Django 5.0.1 on 2024-02-28 03:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_hotel_drive_restaurante_drive_tour_drive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='currentUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 3, 10, 28, 606016, tzinfo=datetime.timezone.utc)),
        ),
    ]
