# Generated by Django 5.0.1 on 2024-02-29 21:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_tour_currentuser_tour_lastmodify'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='currentUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUserBoleto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boleto',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 21, 36, 28, 951140, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='guiado',
            name='currentUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUserGuiado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guiado',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 21, 36, 28, 953863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='hotel',
            name='currentUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUserHotel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 21, 36, 28, 949359, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='currentUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUserRest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 21, 36, 28, 950335, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='transporte',
            name='currentUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUserTransporte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transporte',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 21, 36, 28, 952620, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='traslado',
            name='currentUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUserTraslado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traslado',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 21, 36, 28, 951622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='tren',
            name='currentUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUserTren', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tren',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 21, 36, 28, 952159, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='upselling',
            name='currentUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUserUpselling', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upselling',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 21, 36, 28, 953259, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='currentUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUserTour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tour',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 21, 36, 28, 948345, tzinfo=datetime.timezone.utc)),
        ),
    ]
