# Generated by Django 5.0.1 on 2024-02-29 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_boleto_currentuser_boleto_lastmodify_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleto',
            old_name='estudianteE',
            new_name='adultoe',
        ),
        migrations.RenameField(
            model_name='boleto',
            old_name='estudianteP',
            new_name='adultop',
        ),
        migrations.RenameField(
            model_name='boleto',
            old_name='ppeAdulto',
            new_name='estudianteExtranjero',
        ),
        migrations.RenameField(
            model_name='boleto',
            old_name='ppeInfante',
            new_name='estudiantePeruano',
        ),
        migrations.RenameField(
            model_name='boleto',
            old_name='ppeNinio',
            new_name='infantee',
        ),
        migrations.RenameField(
            model_name='boleto',
            old_name='pppAdulto',
            new_name='infantep',
        ),
        migrations.RenameField(
            model_name='boleto',
            old_name='pppInfante',
            new_name='ninioe',
        ),
        migrations.RenameField(
            model_name='boleto',
            old_name='pppNinio',
            new_name='niniop',
        ),
        migrations.RenameField(
            model_name='guiado',
            old_name='ptapriv',
            new_name='precioPrivadoe',
        ),
        migrations.RenameField(
            model_name='guiado',
            old_name='ptapull',
            new_name='precioPrivadop',
        ),
        migrations.RenameField(
            model_name='guiado',
            old_name='ptbpriv',
            new_name='precioPulle',
        ),
        migrations.RenameField(
            model_name='guiado',
            old_name='ptbpull',
            new_name='precioPullp',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='drive',
            new_name='fichaTecnica',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='horarioDesayuno',
            new_name='horarioDesayunoFinal',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='figma',
            new_name='pdfProveedor',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='telefono',
            new_name='telefonoReserva',
        ),
        migrations.RenameField(
            model_name='restaurante',
            old_name='drive',
            new_name='fichaTecnica',
        ),
        migrations.RenameField(
            model_name='restaurante',
            old_name='figma',
            new_name='pdfProveedor',
        ),
        migrations.RenameField(
            model_name='restaurante',
            old_name='precioMenuE',
            new_name='precioCarta',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='drive',
            new_name='fichaTecnica',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='figma',
            new_name='pdfProveedor',
        ),
        migrations.RenameField(
            model_name='transporte',
            old_name='ppe',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='traslado',
            old_name='ppe',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='tren',
            old_name='precioAdulto',
            new_name='adulto',
        ),
        migrations.RenameField(
            model_name='tren',
            old_name='precioInfante',
            new_name='infante',
        ),
        migrations.RenameField(
            model_name='tren',
            old_name='precioNinio',
            new_name='ninio',
        ),
        migrations.RenameField(
            model_name='upselling',
            old_name='ppe',
            new_name='pne',
        ),
        migrations.RenameField(
            model_name='upselling',
            old_name='ppp',
            new_name='pnp',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='ppp',
        ),
        migrations.RemoveField(
            model_name='traslado',
            name='ppp',
        ),
        migrations.AddField(
            model_name='hotel',
            name='horarioDesayunoInicio',
            field=models.TimeField(default='0:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='precioConfidencial',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='categoria',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='pe',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='recomendacionesImagen',
            field=models.CharField(default='  ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upselling',
            name='pve',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upselling',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleto',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 23, 51, 1, 834702, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guiado',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 23, 51, 1, 837273, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 23, 51, 1, 832527, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 23, 51, 1, 833736, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 23, 51, 1, 831188, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 23, 51, 1, 836241, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 23, 51, 1, 835222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tren',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 23, 51, 1, 835772, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='upselling',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 23, 51, 1, 836698, tzinfo=datetime.timezone.utc)),
        ),
    ]
