# Generated by Django 5.0.1 on 2024-03-01 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_rename_estudiantee_boleto_adultoe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnicahotel',
            name='Hotel',
        ),
        migrations.RemoveField(
            model_name='fichatecnicarestaurante',
            name='Restaurante',
        ),
        migrations.AlterField(
            model_name='boleto',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 14, 50, 21, 985106, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guiado',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 14, 50, 21, 991017, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 14, 50, 21, 979765, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 14, 50, 21, 982218, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 14, 50, 21, 978533, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 14, 50, 21, 989337, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 14, 50, 21, 987146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tren',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 14, 50, 21, 988414, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='upselling',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 14, 50, 21, 990067, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='FichaTecnica',
        ),
        migrations.DeleteModel(
            name='FichaTecnicaHotel',
        ),
        migrations.DeleteModel(
            name='FichaTecnicaRestaurante',
        ),
    ]
