# Generated by Django 5.0.1 on 2024-03-02 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_remove_fichatecnicahotel_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 21, 54, 49, 992624, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guiado',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 21, 54, 49, 995053, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 21, 54, 49, 991465, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 21, 54, 49, 992055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 21, 54, 49, 990607, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 21, 54, 49, 994109, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 21, 54, 49, 993103, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tren',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 21, 54, 49, 993568, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='upselling',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 21, 54, 49, 994577, tzinfo=datetime.timezone.utc)),
        ),
    ]
