# Generated by Django 5.0.1 on 2024-03-05 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_alter_boleto_lastmodify_alter_guiado_lastmodify_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='ppe',
            new_name='pne',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='ppp',
            new_name='pnp',
        ),
        migrations.AlterField(
            model_name='boleto',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 19, 15, 13, 672186, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guiado',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 19, 15, 13, 674886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 19, 15, 13, 670880, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 19, 15, 13, 671526, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 19, 15, 13, 670110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 19, 15, 13, 673862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 19, 15, 13, 672733, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tren',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 19, 15, 13, 673286, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='upselling',
            name='lastModify',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 19, 15, 13, 674371, tzinfo=datetime.timezone.utc)),
        ),
    ]
