# Generated by Django 5.0.1 on 2024-02-07 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfauth', '0005_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 14, 58, 9, 50975, tzinfo=datetime.timezone.utc)),
        ),
    ]
