# Generated by Django 5.0.1 on 2024-02-07 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfauth', '0007_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 15, 4, 15, 508237, tzinfo=datetime.timezone.utc)),
        ),
    ]
