# Generated by Django 5.0.1 on 2024-02-07 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfauth', '0010_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 15, 17, 44, 579654, tzinfo=datetime.timezone.utc)),
        ),
    ]
