# Generated by Django 5.0.1 on 2024-02-17 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfauth', '0015_customuser_role_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 23, 57, 39, 770888, tzinfo=datetime.timezone.utc)),
        ),
    ]
