# Generated by Django 5.0.1 on 2024-02-20 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfauth', '0018_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 13, 21, 43, 374631, tzinfo=datetime.timezone.utc)),
        ),
    ]
