# Generated by Django 5.0.1 on 2024-02-23 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfauth', '0021_alter_customuser_date_joined_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 15, 26, 59, 22417, tzinfo=datetime.timezone.utc)),
        ),
    ]
