# Generated by Django 5.0.1 on 2024-02-29 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfauth', '0025_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 23, 51, 1, 812691, tzinfo=datetime.timezone.utc)),
        ),
    ]
