# Generated by Django 5.0.1 on 2024-03-01 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfauth', '0026_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 14, 50, 21, 952549, tzinfo=datetime.timezone.utc)),
        ),
    ]
