# Generated by Django 5.0.1 on 2024-03-02 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfauth', '0027_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 21, 54, 49, 987063, tzinfo=datetime.timezone.utc)),
        ),
    ]
